//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8784
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPInformer2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPInformer2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addfont; Arial;9;Bold;Group;
        ///addfont; Microsoft Sans Serif;8;Regular;Names;
        ///addfont; Arial;14;Bold;Slogan;
        ///
        ///scene;20;
        ///addstring;IP Informer;Group;
        ///addstring;v 0.1.2;Group;
        ///addstring;Распространяется бесплатно;Names;
        ///addstring;                      ;Names;
        ///addstring;Developers;Group;
        ///addstring;[Wildsoft], [Chaos Software];Group;
        ///addstring;                      ;Names;
        ///addstring;Idea by;Group;
        ///addstring;OPPosition;Names;
        ///addstring;Code by;Group;
        ///addstring;Hex_Laden;Names;
        ///addstring;Chang Min H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap arrow_full_down_32 {
            get {
                object obj = ResourceManager.GetObject("arrow_full_down_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_full_left_32 {
            get {
                object obj = ResourceManager.GetObject("arrow_full_left_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_full_right_32 {
            get {
                object obj = ResourceManager.GetObject("arrow_full_right_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_full_up_32 {
            get {
                object obj = ResourceManager.GetObject("arrow_full_up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip|IP-адрес
        ///country_iso|Код страны
        ///country_lat|Широта страны
        ///country_lon|Долгота страны
        ///country_name_ru|Страна
        ///country_name_en|Страна (ENG)
        ///city_lat|Широта города
        ///city_lon|Долгота города
        ///city_name_ru|Город
        ///city_name_en|Город (ENG)
        ///region_name_ru|Регион
        ///region_name_en|Регион (ENG)
        ///region_iso|Код региона
        ///status|Статус
        ///field|Источник IP.
        /// </summary>
        internal static string datastructure {
            get {
                return ResourceManager.GetString("datastructure", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap edit_svg {
            get {
                object obj = ResourceManager.GetObject("edit_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ip_blue_16x16 {
            get {
                object obj = ResourceManager.GetObject("ip_blue_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ip_gray_16x16 {
            get {
                object obj = ResourceManager.GetObject("ip_gray_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ip_green_16x16 {
            get {
                object obj = ResourceManager.GetObject("ip_green_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ip_icon_form {
            get {
                object obj = ResourceManager.GetObject("ip_icon_form", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ip_off_16x16 {
            get {
                object obj = ResourceManager.GetObject("ip_off_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ip_red_16x16 {
            get {
                object obj = ResourceManager.GetObject("ip_red_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ip_yellow_16x16 {
            get {
                object obj = ResourceManager.GetObject("ip_yellow_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan;AF
        ///Aland Islands;AX
        ///Albania;AL
        ///Algeria;DZ
        ///American Samoa;AS
        ///Andorra;AD
        ///Angola;AO
        ///Anguilla;AI
        ///Antarctica;AQ
        ///Antigua and Barbuda;AG
        ///Argentina;AR
        ///Armenia;AM
        ///Aruba;AW
        ///Australia;AU
        ///Austria;AT
        ///Azerbaijan;AZ
        ///Bahamas;BS
        ///Bahrain;BH
        ///Bangladesh;BD
        ///Barbados;BB
        ///Belarus;BY
        ///Belgium;BE
        ///Belize;BZ
        ///Benin;BJ
        ///Bermuda;BM
        ///Bhutan;BT
        ///Bolivia, Plurinational State of;BO
        ///Bonaire, Sint Eustatius and Saba;BQ
        ///Bosnia and Herzegovina;BA
        ///Botswana;BW
        ///Bouvet Island;BV
        ///Brazil;BR
        ///British Indian Ocean Territory;IO
        ///Brunei Darussalam;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iso {
            get {
                return ResourceManager.GetString("iso", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NewDataSet&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;ComAlarmLevel&gt;0&lt;/ComAlarmLevel&gt;
        ///    &lt;ComTime&gt;0&lt;/ComTime&gt;
        ///    &lt;ComNetErr&gt;1&lt;/ComNetErr&gt;
        ///    &lt;ComScriptChange&gt;0&lt;/ComScriptChange&gt;
        ///    &lt;ComTimeInterval&gt;30&lt;/ComTimeInterval&gt;
        ///    &lt;ComAlarmSound&gt;true&lt;/ComAlarmSound&gt;
        ///    &lt;ComNewIPMessage&gt;true&lt;/ComNewIPMessage&gt;
        ///    &lt;ComCheckExit&gt;false&lt;/ComCheckExit&gt;
        ///    &lt;ComAlarmSoundPath /&gt;
        ///    &lt;ComRunCommand /&gt;
        ///  &lt;/appSettings&gt;
        ///  &lt;ScriptsList&gt;
        ///    &lt;URL&gt;https://api.myip.com/&lt;/URL&gt;
        ///  &lt;/ScriptsLi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main_def {
            get {
                return ResourceManager.GetString("main_def", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap minus_svg {
            get {
                object obj = ResourceManager.GetObject("minus_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overlay {
            get {
                object obj = ResourceManager.GetObject("overlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream panicsound {
            get {
                return ResourceManager.GetStream("panicsound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap plus_svg {
            get {
                object obj = ResourceManager.GetObject("plus_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap question1 {
            get {
                object obj = ResourceManager.GetObject("question1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sound {
            get {
                object obj = ResourceManager.GetObject("sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
